#!/usr/bin/env python3
"""
Play a Yamaha Playcard on the emulated MSX, with sound.

    python play_card.py <card.bin> [options]

Starts openMSX with the UPA-01 cartridge, waits for the cartridge's menu,
presses F1 to engage the card reader, feeds it the card image through a
software stand-in for the CR-01 reader, and then starts playback.

openMSX has no Playcard reader, so the card is injected by breakpointing the
two places the cartridge reads its reader port at 0x7FFF and answering them
directly.  See fake_cr01.tcl for how that works.

Two details matter, and both come from how a real card behaves:

  * After the recorded data the rest of the magnetic strip is blank, so the
    reader is fed a run of zero bits before going inactive.  A zero block type
    is the format's own end-of-data marker, which is how the cartridge knows
    the card is finished rather than spinning waiting for more.

  * Some cards start playing by themselves as soon as they are read (Silent
    Night, When You Wish Upon a Star); others wait to be started (Jingle Bells,
    Love Me Tender).  F2 is a play/stop *toggle*, so pressing it on a card that
    already started stops it.  Nothing is pressed by default; pass --press-play
    for the cards that need it.  The on-screen Play-mode field is not a
    reliable indicator, so it is not used to decide.

Progress is printed to the terminal as it happens, so nothing needs to be read
off the emulator window.

Options:
    --seconds N   stop automatically after N seconds
    --machine M   MSX machine to use          (default yamaha_cx5m)
    --openmsx P   path to openmsx.exe         (default: found on PATH, or
                  $OPENMSX_PATH, or the usual install locations)
    --cart P      path to the UPA-01 ROM
    --wav P       also capture the emulator's audio to this .wav
    --trailer N   zero bits fed after the card data (default 4000)
    --press-play  press F2 after loading; cards that self-start do not need it,
                  and pressing it on those would stop them (F2 is a toggle)
    --keep        leave the generated Tcl script in place for inspection
"""

import argparse, os, shutil, subprocess, sys, tempfile, time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import playcard_decode as P

def find_openmsx():
    """openmsx on PATH, or OPENMSX_PATH, or a few usual places.

    There is no default install path worth hard-coding, and there used to be
    one here that only existed on the machine this was written on.  --openmsx
    overrides whatever this finds."""
    env = os.environ.get('OPENMSX_PATH')
    if env and os.path.isfile(env):
        return env
    for name in ('openmsx.exe', 'openmsx'):
        found = shutil.which(name)
        if found:
            return found
    for guess in (r'C:/Program Files/openMSX/openmsx.exe',
                  r'C:/Program Files (x86)/openMSX/openmsx.exe',
                  '/usr/bin/openmsx', '/usr/local/bin/openmsx',
                  '/Applications/openMSX.app/Contents/MacOS/openmsx'):
        if os.path.isfile(guess):
            return guess
    return 'openmsx.exe'          # so the error message names something


DEF_OPENMSX = find_openmsx()
# The cartridge ROM is Yamaha's and is not in this repository; it lives in
# Roms/, or wherever PLAYCARD_ROMS points.  Resolved at run time so that
# --help works without it.
DEF_CART = os.path.join(P.ROM_DIR, P.CART_ROM)

TCL = r'''
# Generated by play_card.py - plays one Playcard on the emulated MSX.
set ::card    {%(card)s}
set ::logfile {%(log)s}
set ::autostop %(autostop)s
set ::wav      {%(wav)s}
set ::trailer  %(trailer)s
set ::pressplay %(pressplay)s

set ::log [open $::logfile w]
proc emit {m} { puts $::log $m; flush $::log }

set fh [open $::card rb]
fconfigure $fh -translation binary
set ::carddata [read $fh]
close $fh
binary scan $::carddata B* ::bits
set ::nbits [string length $::bits]
set ::total [expr {$::nbits + $::trailer}]
set ::bitpos 0

emit "card: $::card"
emit "size: [string length $::carddata] bytes ($::nbits bits, + $::trailer blank)"

# ---- stand-in for the CR-01 reader at 0x7FFF -------------------------------
# bit 7 = reader active, bit 6 = a bit is ready, bit 5 = the data bit.
# Past the recorded data we hand out zeros, like the blank tail of the strip,
# then drop bit 7 as the card leaves the reader.
proc cr01_poll {} {
    if {$::bitpos < $::total} { reg A 0x80 } else { reg A 0x00 }
    reg PC 0x6895
}
proc cr01_bit {} {
    if {$::bitpos >= $::total} {
        reg A 0x00
    } else {
        if {$::bitpos < $::nbits} {
            set b [string index $::bits $::bitpos]
        } else {
            set b "0"
        }
        incr ::bitpos
        reg A [expr {0xC0 | ($b eq "1" ? 0x20 : 0x00)}]
    }
    reg PC 0x68B5
}

proc rowtext {n} {
    set base [expr {[debug read "VDP regs" 2] * 0x400}]
    binary scan [debug read_block VRAM [expr {$base + $n*32}] 32] cu* bytes
    set s {}
    foreach b $bytes {
        if {$b >= 32 && $b < 127} { append s [format %%c $b] } else { append s " " }
    }
    return [string trimright $s]
}

proc playmode {} { return [string trim [string range [rowtext 9] 20 end]] }

proc screen {} {
    for {set row 0} {$row < 24} {incr row} {
        set s [rowtext $row]
        if {$s ne ""} { emit "    $s" }
    }
}

proc press {row mask} {
    keymatrixdown $row $mask
    after time 1 [list keymatrixup $row $mask]
}

proc boot_done {} {
    emit "STATUS cartridge menu is up"
    debug set_bp 0x6892 {} {cr01_poll}
    debug set_bp 0x68B2 {} {cr01_bit}
    emit "STATUS reader armed; pressing F1 (card-read)"
    press 6 0x20
    after time 2 check_read
}

proc check_read {} {
    if {$::bitpos >= $::nbits} {
        emit "STATUS card data read: $::nbits bits"
        after time 3 check_trailer
    } else {
        emit "STATUS reading... $::bitpos of $::nbits bits"
        after time 2 check_read
    }
}

proc check_trailer {} {
    emit "STATUS blank tail fed: [expr {$::bitpos - $::nbits}] of $::trailer bits"
    if {$::wav ne ""} {
        if {[catch {soundlog start $::wav} e]} {
            emit "STATUS sound capture failed: $e"
        } else {
            emit "STATUS capturing audio to $::wav"
        }
    }
    after time 2 maybe_play
}

# F2 is a play/stop toggle.  Some cards start on their own once read; pressing
# F2 on those stops them.  The Play-mode field does not sit steadily on "play"
# while running, so sample it repeatedly and treat any single "play" as proof
# that the card is already going.
proc maybe_play {} {
    if {$::pressplay} {
        emit "STATUS pressing F2 to start (--press-play)"
        press 6 0x40
    } else {
        emit "STATUS not pressing F2; this card should start on its own."
        emit "STATUS   if you hear nothing, re-run with --press-play"
    }
    after time 3 report
}

proc report {} {
    emit "SCREEN:"
    screen
    emit "STATUS Play-mode is now \"[playmode]\" - listen"
    if {$::autostop > 0} { after realtime $::autostop quit_now }
}

proc quit_now {} {
    catch {soundlog stop}
    emit "STATUS stopping"
    close $::log
    exit
}

after time 6 boot_done
'''


def main():
    ap = argparse.ArgumentParser(description='Play a Yamaha Playcard on the emulated MSX.')
    ap.add_argument('card', help='the .bin card image to play')
    ap.add_argument('--seconds', type=int, default=0,
                    help='stop automatically after N seconds')
    ap.add_argument('--machine', default='yamaha_cx5m')
    ap.add_argument('--openmsx', default=DEF_OPENMSX)
    ap.add_argument('--cart', default=DEF_CART)
    ap.add_argument('--wav', default='', help="also capture the emulator's audio to this .wav")
    ap.add_argument('--trailer', type=int, default=4000,
                    help='zero bits fed after the card data (default 4000)')
    ap.add_argument('--press-play', action='store_true', dest='pressplay',
                    help='press F2 after loading (needed by cards that do not self-start)')
    ap.add_argument('--keep', action='store_true')
    a = ap.parse_args()

    card = os.path.abspath(a.card)
    P.check_card(card)          # before openMSX is started for nothing
    n = os.path.getsize(card)
    if not (100 < n < 2000):
        print('warning: %d bytes is an unusual size for a Playcard image' % n)
    if not os.path.isfile(a.openmsx):
        sys.exit('openmsx.exe not found at %s (use --openmsx)' % a.openmsx)
    if not os.path.isfile(a.cart):
        sys.exit('UPA-01 cartridge ROM not found at %s (use --cart)' % a.cart)

    tmp = tempfile.mkdtemp(prefix='playcard_')
    log = os.path.join(tmp, 'status.txt')
    tcl = os.path.join(tmp, 'play.tcl')
    with open(tcl, 'w') as f:
        f.write(TCL % {'card': card.replace(os.sep, '/'),
                       'log': log.replace(os.sep, '/'),
                       'autostop': a.seconds,
                       'trailer': a.trailer,
                       'pressplay': 1 if a.pressplay else 0,
                       'wav': os.path.abspath(a.wav).replace(os.sep, '/') if a.wav else ''})

    print('card    : %s (%d bytes)' % (os.path.basename(card), n))
    print('machine : %s' % a.machine)
    print('starting openMSX; sound comes from the emulator itself.')
    if a.seconds:
        print('will stop after %d seconds.' % a.seconds)
    else:
        print('press Ctrl+C here to stop.')
    print('-' * 60)

    proc = subprocess.Popen([a.openmsx, '-machine', a.machine, '-cart', a.cart,
                             '-script', tcl],
                            cwd=os.path.dirname(a.openmsx) or None,
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    seen = 0
    try:
        while proc.poll() is None:
            if os.path.exists(log):
                with open(log) as f:
                    lines = f.read().splitlines()
                for line in lines[seen:]:
                    print(line)
                seen = len(lines)
            time.sleep(0.4)
    except KeyboardInterrupt:
        print('\nstopping.')
    finally:
        if proc.poll() is None:
            proc.terminate()
        if os.path.exists(log):
            with open(log) as f:
                lines = f.read().splitlines()
            for line in lines[seen:]:
                print(line)
        if not a.keep:
            for p in (tcl, log):
                try:
                    os.remove(p)
                except OSError:
                    pass
            try:
                os.rmdir(tmp)
            except OSError:
                pass
        else:
            print('kept: %s' % tmp)


if __name__ == '__main__':
    P.run(main)
